### ISSUE TITLE
Two things, mainly how can i open Windhawk?

### ISSUE THREAD

**Issue by Kiwikairii** [teknixstuff/revert8plus#14]
i want to disable the kill appframe UWP mod, but i can't seem to find a way to open windhawk, and the executable located in program data doesn't open at all.

And also would like to know why does clicking "pin to start menu" pins it to the taskbar on startisback? is that a windhawk mod or what is going on there? Overall im absolutely loving using revert8plus but these two things are bugging me out.

Thanks in advance!

**Comment by Kiwikairii** [comment]
managed to find the .dll file for the uwp mod and move it, but still cannot find a fix for the pin to start menu thing.

**Comment by teknixstuff** [comment]
> i want to disable the kill appframe UWP mod, but i can't seem to find a way to open windhawk, and the executable located in program data doesn't open at all.
> 
> And also would like to know why does clicking "pin to start menu" pins it to the taskbar on startisback? is that a windhawk mod or what is going on there? Overall im absolutely loving using revert8plus but these two things are bugging me out.
> 
> Thanks in advance!

Run C:\Windows\Revert8Plus\instextras.exe, install the windhawk UI, then the executable in programdata will work again.

**Comment by Kiwikairii** [comment]
Hi, im on the 3.4.4 release and i cannot find instextras.exe where you pointed to... 

either way, would this fix the "pin to start menu" problem? because that is the only one im really looking for at the moment.

**Comment by Kiwikairii** [comment]
i see! thanks for the response!!
