### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Maximusgamer2109** [teknixstuff/revert8plus#16]
Tried to use stable version, didn't work, so i used the latest build and it doesn't work. latest windows 10 build currently at 22h2

**Comment by Nukley** [comment]
Same here, and I have 21H2, the latest stable did work, but the aero buttons on the title bar did not.

**Comment by SlippingGitty** [comment]
Ditto, I am unable to execute the command from Run.exe on Windows 11 24H2

**Comment by teknixstuff** [comment]
This isn't my fault. Netcraft and abuse.ch keep reporting pages of my site as phishing and breaking both the install command and the site itself. You'll have to download either the [test build offline installer](https://github.com/teknixstuff/revert8plus/releases) or the [v3.3.4 offline installer](https://github.com/teknixstuff/revert8plus/releases/download/3.3.4/r8p.exe)
