### ISSUE TITLE
When updating r8p it wasnt successful and reverted all back to the boring windows 11

### ISSUE THREAD

**Issue by Alejandrix2456github** [teknixstuff/revert8plus#21]
And to the worse when i try to download it every antivirus ndoes detect it as a virus and removes it, i tried downloading with Edge, Brave and nothing they just keeped cancelling it cuz its a virus and i dont wanna stay with the boring Windows 11 Normal style, and i tried from pale moon and voila it did with pale moon and defender did not remove it

**Comment by Alejandrix2456github** [comment]
and i launched but IT WASNT COMPATIBLE

**Comment by Alejandrix2456github** [comment]
please remove new Setup GUI it makes it keep being unsuccessful for me and reverts it to the boring windows 11

**Comment by Alejandrix2456github** [comment]
and got a older version and works just fine

**Comment by teknixstuff** [comment]
Antivirus flags are not my fault. If you get a "The transformation was not successful" error then please send a screenshot of the error message.

**Comment by Alejandrix2456github** [comment]
![2024-12-27 19_06_55-r8p exe](https://github.com/user-attachments/assets/10d178c6-e7e9-47ef-bc3c-bc0d7919428a)
UHGFUGHGDHG
