### ISSUE TITLE
Installer window doesn't render on high DPI (150%)

### ISSUE THREAD

**Issue by sheben112** [teknixstuff/revert8plus#22]
(when opened)
![image](https://github.com/user-attachments/assets/ab2f43a7-3605-4d23-b676-d5e6fff817b4)
(after a few minutes)
![image](https://github.com/user-attachments/assets/3fe3dc00-8165-4139-8580-5a8a1f35e40d)
this is on windows 11 22h2, i dont have any programs that change windows' apperance or themes installed

**Comment by sheben112** [comment]
this is on test build 1078, the latest as of writing this

**Comment by xYannikx** [comment]
Are you using scaling? For me, the problem was solved when I switched from 150% to 100%

**Comment by sheben112** [comment]
this worked but im gonna leave the issue up since high dpi should be worked on

**Comment by teknixstuff** [comment]
> this worked but im gonna leave the issue up since high dpi should be worked on

This has now been fixed
