### ISSUE TITLE
The LibreWolf new tab issue

### ISSUE THREAD

**Issue by AND2180K** [teknixstuff/revert8plus#23]
On the newest test build (Test Build 1082), when I open a new tab in the LibreWolf browser, it immediately gives the error "Tab crashed" and nothing helps to fix this error. I love your project, but without my favorite browser (which should work properly) I can not use my PC the way I want. If you can fix this error in new builds, I will be glad. (if there are errors in the text - sorry, I used a translator) Windows 10 22H2 Build 19045.4239

**Comment by teknixstuff** [comment]
Go to `HKEY_LOCAL_MACHINE\SOFTWARE\Windhawk\Engine\Settings`, and set `Exclude` to `librewolf.exe` (or whatever the librewolf EXE name is). That will exclude it from r8p.

**Comment by teknixstuff** [comment]
If you have multiple EXE files you need to exclude, separate their names with commas.

**Comment by AND2180K** [comment]
Thanks
