### ISSUE TITLE
Problem with favorites tab in explorer

### ISSUE THREAD

**Issue by AND2180K** [teknixstuff/revert8plus#24]
On the newest test build (Test Build 1082), when I go to the favorites tab in Explorer, literally none of my bookmarks are displayed. This can be fixed by going to Winaero Tweaker and changing the home page from "This PC" to "Favorites". But even in this case there is a problem, because the favorites tab does not appear at the top, but at the bottom, which is inconvenient for me. (if there are errors in the text - sorry, I used a translator) Windows 10 22H2 Build 19045.4239

**Comment by teknixstuff** [comment]
> On the newest test build (Test Build 1082), when I go to the favorites tab in Explorer, literally none of my bookmarks are displayed. This can be fixed by going to Winaero Tweaker and changing the home page from "This PC" to "Favorites". But even in this case there is a problem, because the favorites tab does not appear at the top, but at the bottom, which is inconvenient for me. (if there are errors in the text - sorry, I used a translator) Windows 10 22H2 Build 19045.4239

Favorites is separate to Quick Access and you will have to re-add any pinned items to favorites.
