### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Timmy193** [teknixstuff/revert8plus#5]
Whenever i install revert8plus forked it says that i have a third party antivirus and i removed it and followed the instructions and then it said that again can y'all fix this problem please? or i am running an old version of revert8plus since i have the version that was released and i heard about 6 months ago?

**Comment by teknixstuff** [comment]
> Whenever i install revert8plus forked it says that i have a third party antivirus and i removed it and followed the instructions and then it said that again can y'all fix this problem please? or i am running an old version of revert8plus since i have the version that was released and i heard about 6 months ago?

Most antiviruses do not correctly unregister themselves after being uninstalled, so the warning remains, but as long as you are sure it is uninstalled, you can continue safely.
