### ISSUE TITLE
UWP Apps don’t open, Maximizing is Broken

### ISSUE THREAD

**Issue by CreeperofDoom** [teknixstuff/revert8plus#8]
After installing Revert8Plus (Stable Release) It works perfectly fine. But UWP Apps such as Settings and Microsoft store do not open.

Also, Maximizing a Window in any Program it doesn’t maximize completely and to the Bottom and Right it shows part of the Desktop

**Comment by teknixstuff** [comment]
This is a known issue on Windows 11, and it will be fixed in v4.
